spark-streaming {
  input-dir       = "images"
  output-dir      = "output"
  checkpoint-dir  = "checkpoints"
  simulator-interval-ms = 5000
  window-duration = "10 minutes"
  watermark-duration = "2 minutes"
}
